services:
  app:
    build: .
    container_name: node_app
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./server/data:/app/server/data
    env_file:
      - .env
    restart: unless-stopped
